# -*- coding: utf-8 -*-
"""Analítica de negocios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIHLV1-FJubyVlZgulIZoAtteIbvarlb

# **DECLARACION DE VARIABLES**
---

*almacenamiento de variables/información*
"""

a = 3

a

a = 4

a

b = 5

"""## **COMBINACIÓN DE VARIABLES**"""

a+b

a*b

a**b





"""# **LIMPIEZA DE DATOS**

##1. Importar librerias
Las librerias que vamos a usar pandas, mat, seaborn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""##2. Cargar datos

*Vamos a leer los datos*
*df sera donde quedara toda nuestra info (**data frame**)*
"""

#Determinación de variables
df = pd.read_excel('/content/Panaderia_Desc.xlsx')

"""**Formas de familiarizarnos con la data**"""

df.head()

"""***Df.info** nos permite veririficar que tan grande puede ser la data, formatos, tipos de variable*
*Ejemplo*
* *int: variable entera*
* *date time*
* *object: texto ó cadanea de caracteres (promoción)*
* *Float: Variables con decimales, tambien quiere decir continuas*
* *non: datos no nulos*

"""

df.info()

#asi detectamos cuantos nulos hay
#tenemos 98% de los datos ya que el 2% se encuentra nulo
df.isnull().sum()

df.duplicated().sum()

